name: Build Server
on:
  push:
    branches: development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          debug: true
          allenvs: true
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm --help
            cd /home/project/caleg-rika
            whereis node
            whereis npm
            npm ls -g --depth=0
            pwd
            git status
            git fetch origin
            git pull origin development --rebase
            yarn
            yarn build
            pm2 restart ecosystem.config.js
