name: Build Server
on:
  push:
    branches: development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /home/project/caleg-rika
            whoami
            pwd
            git status
            git fetch
            git pull --rebase
            yarn install
            yarn build
            pm2 restart ecosystem.config.js
